language: go
sudo: false

os:
  - linux

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

install:
  - echo "This is an override of the default install deps step in travis."

script:
  - go get -u -v ./...
  - go build -v .
  - go vet $(go list ./...)
  - go test $(go list ./...)
